// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gapubksmrjxkzjkobepx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhcHVia3Ntcmp4a3pqa29iZXB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNTkyNzksImV4cCI6MjA3MjczNTI3OX0.x0GUoD3g3NHsw8xaTeAhFuCrAOYMUVALplMeGhfF15w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});